### ISSUE TITLE
Unnecessary dropwizard-core dependency?

### ISSUE THREAD

**Issue by sjoerdtalsma** [opentracing-contrib/java-dropwizard#5]
Although the library is called dropwizard-opentracing, there only seems to be a _jersey_ dependency (at least in the jersey-2 version).

Shouldn't the library be renamed to jersey2-opentracing or something more appropriate?
We now pull in the entire dropwizard-core including impressive transitive tree:

- dropwizard-util
- dropwizard-jackson
- dropwizard-validation
- dropwizard-configuration
- dropwizard-logging
- dropwizard-metrics
- dropwizard-jersey
- dropwizard-servlets
- dropwizard-jetty
- dropwizard-lifecycle
- metrics-core
- metrics-jvm
- metrics-servlets
- metrics-healthchecks
- argparse4j
- jetty-setuid-java

**Comment by sjoerdtalsma** [comment]
Is this library still necessary?
Or will it be replaced by something like: https://github.com/opentracing-contrib/java-jaxrs

**Comment by malafeev** [comment]
it should be deprecated.
