### ISSUE TITLE
Support ActiveSpanProvider

### ISSUE THREAD

**Issue by tedsuo** [opentracing-contrib/java-dropwizard#6]
This instrumentation could make use of the ActiveSpan support in the new OT API.

**Comment by malafeev** [comment]
should be closed as will not be fixed.
OpenTracing Java JAX-RS instrumentation support active spans.

**Comment by malafeev** [comment]
https://github.com/opentracing-contrib/java-jaxrs

**Comment by malafeev** [comment]
https://github.com/opentracing-contrib/java-dropwizard/pull/7
